import type { Provider } from '@/types';

export const providersData: Provider[] = [
  {
    id: '1',
    name: 'ARMed Solutions',
    description: 'Pioneering AR applications for surgical planning and intraoperative guidance. Our flagship product enhances precision and patient outcomes.',
    website: 'https://example.com/armed',
    logoUrl: 'https://placehold.co/300x150.png?text=ARMed+Solutions',
    specialties: ['surgery', 'orthopedics', 'neurosurgery'],
    technologies: ['ar', 'surgical navigation', 'medical imaging'],
    contactEmail: 'contact@armed.example.com',
  },
  {
    id: '2',
    name: 'Mixed Reality Training Co.',
    description: 'Immersive MR simulations for medical training and education. We provide realistic scenarios for complex procedures and emergency response.',
    website: 'https://example.com/mrtraining',
    logoUrl: 'https://placehold.co/300x150.png?text=MR+Training+Co',
    specialties: ['medical education', 'simulation', 'emergency medicine'],
    technologies: ['mr', 'vr', 'haptic feedback'],
    contactEmail: 'info@mrtraining.example.com',
  },
  {
    id: '3',
    name: 'VirtuCare Diagnostics',
    description: 'AR-enhanced diagnostic tools and patient visualization platforms. Improving diagnostic accuracy and patient understanding.',
    website: 'https://example.com/virtucare',
    logoUrl: 'https://placehold.co/300x150.png?text=VirtuCare',
    specialties: ['radiology', 'cardiology', 'patient education'],
    technologies: ['ar', 'data visualization', 'remote diagnostics'],
  },
  {
    id: '4',
    name: 'HoloHealth Systems',
    description: 'Comprehensive MR solutions for hospital-wide deployment, including remote consultations and collaborative surgical environments.',
    website: 'https://example.com/holohealth',
    specialties: ['telemedicine', 'hospital administration', 'collaborative surgery'],
    technologies: ['mr', 'cloud platforms', 'iot integration'],
    contactEmail: 'sales@holohealth.example.com',
  },
  {
    id: '5',
    name: 'AR Anatomy Labs',
    description: 'Interactive AR anatomy models for medical students and professionals. Enhancing learning through engaging 3D visualizations.',
    website: 'https://example.com/aranatomy',
    logoUrl: 'https://placehold.co/300x150.png?text=AR+Anatomy',
    specialties: ['medical education', 'anatomy', 'student training'],
    technologies: ['ar', '3d modeling', 'mobile applications'],
  },
  {
    id: '6',
    name: 'RehabMR Solutions',
    description: 'Mixed Reality applications for physical therapy and rehabilitation, offering engaging exercises and progress tracking.',
    website: 'https://example.com/rehabmr',
    specialties: ['physical therapy', 'rehabilitation', 'neurology'],
    technologies: ['mr', 'gamification', 'motion tracking'],
    contactEmail: 'support@rehabmr.example.com',
  },
];
